version: '0.3.0b{build}'

platform:
  - x64

environment:
  nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install -g electron-forge@latest
  - npm install electron-osx-sign@0.4.10 # electron-forge is depending on broken electron-osx-sign@0.4.9, we force 0.4.10
  - npm install

cache:
  - node_modules

build_script:
  - node --version
  - npm --version
  - npm run make

test: off

artifacts:
  - path: 'out\make\squirrel.windows\x64\*.exe'
    name: 'Setup64'
  - path: 'out\make\squirrel.windows\x86\*.exe'
    name: 'Setup86'
