build: off

platform:
  - x86

environment:
  nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install -g electron-forge@latest
  - npm install electron-osx-sign@0.4.10
  - npm install

cache:
  - node_modules

test_script:
  - node --version
  - npm --version

after_test:
  - npm run make