environment:
  nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install npm -g
  - npm install electron-forge -g
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run make

test: off